### ISSUE TITLE
POST requests return 500 status code and empty message regardless of the chaincode response

### ISSUE THREAD

**Issue by ilyapototsky** [olegabu/fabric-starter-rest#13]
If the chaincode returns an HTTP error code on POST request, the response from the REST API is 500 with empty message regardless of the actual response

**Comment by olegabu** [comment]
error messages are now returned by the latest image; error codes as well as individual query responses and endorsement resumts with codes still get masked and not returned: only the error message is returned with http code 500 for everything

**Comment by olegabu** [comment]
error status codes are now returned as http response headers such as
`HTTP/1.1 404 Not Found`
